### ISSUE TITLE
Trie for Router Algorithm

### ISSUE THREAD

**Issue by daneb** [hetznerZA/soar_sc-rack-router#1]
@sheldonh Have you considered using Trie for the routing algorithm?
Not sure if you benched the routing, but MVC frameworks spend 90% of their time routing and 10% executing the application code.

I've implemented one as an [example](https://github.com/daneb/algorithms/blob/master/trees/trie.rb) with [rspec](https://github.com/daneb/algorithms/blob/master/spec/trie_spec.rb) tests

**Comment by evangraan** [comment]
My 2c: A good idea for dictionaries in general, not convinced there is value for us in routing, but a nice comp sci sojourn none-the-less. I think @routes.detect { |r| r.matches?(env) } does what we want well enough.

Sheldon might find more value in Trie than I do. I'd imagine soar_sc implementations would have on average 4 or 5 routes in the web application. There would be approximately no benefit in a Trie structure for such a small routing requirement. You can imaging a base->level1->level2 traversal in a Trie (3 steps through the hierarchy (many more of the Trie has individual characters as nodes!)) being equivalent to finding the endpoint 3rd in the list of five routes, with routes being simple strings, in this case the endpoint would be '/base/level1/level2' (still 3 steps), by simply walking an array. For a set of 5 routes, on average the Trie would be no better than iterating the array, and for 5 nodes, we would not notice the difference if it was (you can do quite a large number of comparisons in a single CPU time slice. I've seen [].detect benchmarks that find an entry in close on 100,000 items in ~20ms)

If we expected large routing table requirements I'd reach for a Hash as well (its already there, no work for me.) Hash implementations already use mechanisms very close to Tries and Trees (one of Trie's uses is dictionaries,) so a dictionary lookup on routes would have a similar effect. Ruby's Hash implementation can be thought of as a breadth-first Tree with an ever-expanding breadth, with linked lists hanging off each branch (bin). The trade-off in ruby is the house-keeping for re-arranging the depth lists below each node when the breadth is expanded due to high volume allocation. Debatable whether this is the best mechanism, but linked lists can be fast and Mr. Matsumoto was up for the linked-list-gymnastics. I would have thought a Trie could be better, but Yukihiro thought of a rather clever way of binning and arranging that works quite well. In fact, I'm not sure the cost of maintaining a Trie would not outstrip that of Matt's hashed binning for most large trees. Hard to tell without running the numbers. I expect ruby's Hash would support thousands of routing entry lookups with good performance. I'd reach for that first. 

Also, our services would in fact spend orders of magnitudes more time in the model and view and architecture aspects than routing. Much of the routing also would be done outside the soar_sc router. This is because requests would be directed to a large extent in our SOA cloud. I.e. there is routing outside the soar_sc router, such as in the addressing mechanisms (e.g. service registry, URIs in configuration, queue addressing, etc.) Routing in the web application for us then is more of a connecting-the-dots-you-know-you-want-to-connect service, than routing hurtling down deep multi-branched hierarchies to find the best matching node in no time. Ours is routing that greets you and opens the door, as opposed to the valet that leads you up the steps and into you room, lingering for a tip.

Thanks for an interesting topic to ponder.

**Comment by daneb** [comment]
Aloha
Just noticed some implementations of Routers  using Trie, from a standard a Go standard library to others in Ruby and JavaScript. 
But your response is spot on, thank you and didn't realize that Ruby Hashes had a level of "binning".
D

    _____________________________

**Comment by sheldonh** [comment]
I put waaay too much time into optimization in soar_sc-rack-router. But
when I actually profiled it, I was disappointed: I was pissing about in a
tiny portion of the problem space. Most of the work goes into making path
parameters available via Rack::Request#params.

So if you're looking to optimize our routing, the place to look is in
Rack::Request#update_param.

Ciao,
Sheldon.



On Sun, May 15, 2016 at 9:42 PM, Dane Balia <notifications@github.com>
wrote:

> Have you considered using Trie for the routing algorithm?
> Not sure if you benched the routing, but MVC frameworks spend 90% of their
> time routing and 10% executing the application code.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hetznerZA/soar_sc-rack-router/issues/1>
>



-- 
Sheldon Hearn
System Administrator
Hetzner (Pty) Ltd

SA Contact Centre: (T) 0861 0861 08 | (F) 0861 0861 09
International: (T) +27 21 970 2000 | (F) +27 21 970 2001

Registration Number: 2005/023926/07
Directors: D.M. de Villiers (MD), S.M. Nortjé & H.E. Wencke

Web: www.hetzner.co.za
Disclaimer: www.hetzner.co.za/email-disclaimer
